CREATE TYPE color_enum as ENUM('GREEN', 'WHITE', 'BLACK', 'PINK');

CREATE TABLE IF NOT EXISTS cats (
id SERIAL NOT NULL,
name CHARACTER VARYING(20) NOT NULL,
color color_enum DEFAULT 'PINK',
age INT NOT NULL,

PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS dogs (
id SERIAL NOT NULL,
name CHARACTER VARYING(20) NOT NULL,
host_name CHARACTER VARYING(15) NOT NULL,
city CHARACTER VARYING(25) NOT NULL,

PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS writers (
id SERIAL NOT NULL,
wtype CHARACTER VARYING(25) NOT NULL,
name CHARACTER VARYING(20) NOT NULL,
age INT NOT NULL,
poem_name CHARACTER VARYING(30),
page_count INT,
data CHARACTER VARYING(1024),

PRIMARY KEY(id)
);
